In [1]:
import pandas as pd
squirrels = pd.read_csv('data/2018_Central_Park_Squirrel_Census_Data.csv')
squirrels.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9688574691102 40.7837825208444)
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,NaN,Gray,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.97428114848522 40.775533619083)
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9596413903948 40.7903128889029)
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9702676472613 40.7762126854894)

In [2]:
squirrels.describe

<bound method NDFrame.describe of               X          Y Unique Squirrel ID Hectare Shift      Date  \
0    -73.956134  40.794082     37F-PM-1014-03     37F    PM  10142018
1    -73.968857  40.783783     21B-AM-1019-04     21B    AM  10192018
2    -73.974281  40.775534     11B-PM-1014-08     11B    PM  10142018
3    -73.959641  40.790313     32E-PM-1017-14     32E    PM  10172018
4    -73.970268  40.776213     13E-AM-1017-05     13E    AM  10172018
...         ...        ...                ...     ...   ...       ...
3018 -73.963943  40.790868     30B-AM-1007-04     30B    AM  10072018
3019 -73.970402  40.782560     19A-PM-1013-05     19A    PM  10132018
3020 -73.966587  40.783678     22D-PM-1012-07     22D    PM  10122018
3021 -73.963994  40.789915     29B-PM-1010-02     29B    PM  10102018
3022 -73.975479  40.769640      5E-PM-1012-01     05E    PM  10122018

      Hectare Squirrel Number    Age Primary Fur Color  \
0                           3    NaN               NaN
1                           4    NaN               NaN
2                           8    NaN              Gray
3                          14  Adult              Gray
4                           5  Adult              Gray
...                       ...    ...               ...
3018                        4  Adult              Gray
3019                        5  Adult              Gray
3020                        7  Adult              Gray
3021                        2    NaN              Gray
3022                        1  Adult          Cinnamon

         Highlight Fur Color  ...   Kuks  Quaas  Moans Tail flags  \
0                        NaN  ...  False  False  False      False
1                        NaN  ...  False  False  False      False
2                        NaN  ...  False  False  False      False
3                        NaN  ...  False  False  False      False
4                   Cinnamon  ...  False  False  False      False
...                      ...  ...    ...    ...    ...        ...
3018                     NaN  ...  False  False  False      False
3019                   White  ...  False  False  False      False
3020  Black, Cinnamon, White  ...  False  False  False      False
3021         Cinnamon, White  ...  False  False  False      False
3022             Gray, White  ...  False  False  False      False

     Tail twitches  Approaches  Indifferent  Runs from  Other Interactions  \
0            False       False        False      False                 NaN
1            False       False        False      False                 NaN
2            False       False        False      False                 NaN
3            False       False        False       True                 NaN
4            False       False        False      False                 NaN
...            ...         ...          ...        ...                 ...
3018         False       False        False       True                 NaN
3019         False       False         True      False                 NaN
3020         False       False         True      False                 NaN
3021         False       False         True      False                 NaN
3022         False        True        False      False                 NaN

                                        Lat/Long
0     POINT (-73.9561344937861 40.7940823884086)
1     POINT (-73.9688574691102 40.7837825208444)
2     POINT (-73.97428114848522 40.775533619083)
3     POINT (-73.9596413903948 40.7903128889029)
4     POINT (-73.9702676472613 40.7762126854894)
...                                          ...
3018  POINT (-73.9639431360458 40.7908677445466)
3019  POINT (-73.9704015859639 40.7825600069973)
3020  POINT (-73.9665871993517 40.7836775064883)
3021  POINT (-73.9639941227864 40.7899152327912)
3022  POINT (-73.9754794191553 40.7696404489025)

[3023 rows x 31 columns]>